### ISSUE TITLE
11525 - 5 արկղ խնձոր, հայտնի է արկղերի զույգերում եղած խնձորների քանակը

### ISSUE THREAD

**Issue by gogyan** [qarakusi-am/qarakusi.am#113]
http://qarakusi.am/problem/11525/solution

1. Էկրանի մեջտեղում իրար կող նկարել  5 արկղ մանդարին
2. Էկրանի վերևում գրել "Ամբողջը 105 կգ"։
3. Առաջին և երկրորդ արկղերը ձևավոր փակագծով վերևից նշել ու վրան գրել  "39 կգ"
4. Երկրորդ ու երրորդ արկղերի տակը ձևավոր փակագծով գրել "43 կգ"
5. Երրորդ և չորրորդ արկղերի վերևից ձևավոր փակագծով գրել "49 կգ"
6. Չորրորդ ու հինգերորդի տակից ձևավոր փակագծով գրել "42 կգ"։
7. Վերևի երկու փակագծերը տրանսֆորմ անել մի հատ մեծ փակագծի, վրայի թվերն իրար մոտեցնել ու արանքում գրել + նշանը (այս ամենը միաժամանակ):
8. 39+49 տեքստը տանել էկրանի ձախ վերևի մասն ու դիմացից գրել 1) 
9. Վերևի մեծ ձևավոր փակագիծը տրանսֆորմ անել հին ձևի, թվերն էլ հեռացնել ու + նշանը ջնջել։
10. Վերևի կետում արածը շարունակել՝ 1) 39+49=88 կգ։
11. 5-րդ արկղը մեծացնել
12. 9-րդ կետում գրածի տակը գրել 2) 105 - 88 = 17 կգ։
13. 17 կգ–ը տանել 5-րդ արկղի վրա ու արկղը բերել հին չափի։
14.   Կամերան տանել աջ ու մեծացնել, որ 4 ու 5 արկղերը լավ երևան։
15.  Չորրորդ արկղի վրա գրել 42 - 17, որն էլ քիչ անց տրանսֆորմ անել 25 կգ-ի։
16. Կամերան տանել ձախ, որ երևան 3-րդ ու 4-րդ արկղերը։
17. Երրորդի վրա գրել 49-25, որն էլ քիչ անց տրանսֆորմ անել 24-ի։
18. Կամերան հետ տանել ու այդ ընթացքում 2-րդ արկղի վրա գրել 19 կգ, իսկ առաջինի վրա՝ 20 կգ։
19. 25 կգ բերել ու դնել

**Comment by a-arakelian** [comment]
է՞ս խնդիրն ա իմ համար, ոչ մեկի assign արած չի
