### ISSUE TITLE
P12530 - խնձորներով խնդիր, պայմանների քանակ

### ISSUE THREAD

**Issue by gogyan** [qarakusi-am/qarakusi.am#13]
@Gor397  քո առաջին առաջադրանքն է սարքել այս խնդիրը։
Անելուց առաջ զրուցիր @a-arakelian  հետ, տեխնիկական հարցերով քեզ կօգնի @HaykTarkhanyan -ը։
http://qarakusi.am/problem/12530/solution

**Comment by a-arakelian** [comment]
Բարև @Gor397 սա - @ srohund իմ տելեգրամն ա, կարաս ստեղ գրել, կամ էլ ֆեյսբուքով - m.me/mahamorm

**Comment by HaykTarkhanyan** [comment]
Ողջույն @Gor397 , ինչպեսա՞ պրոգրեսը, ինչո՞վ կարանք օգնենք

**Comment by HaykTarkhanyan** [comment]
@Gor397, կներես բավականին ուշ տեսա նամակդ, եթե տելեգրամ օգտագործում ես, որ խնդրեմ մի հատ նամակ կգրես ինձ(t.me/HaykTarkhanyan)՝ կապը ըտեղով պահենք

**Comment by narek-mkrtumyan** [comment]
@Gor397 @a-arakelian էս էլ վիդյոն
https://www.youtube.com/watch?v=8tqll6Zq33Y

**Comment by narek-mkrtumyan** [comment]
https://www.youtube.com/watch?v=lIhdoAbWVJs
