### ISSUE TITLE
P12189 - apples in problems by parts

### ISSUE THREAD

**Issue by gogyan** [qarakusi-am/qarakusi.am#14]
@hakob17  սա էլ քո առաջին առաջադրանքը։
Գրելուց առաջ զրուցիր @a-arakelian  հետ։ 
Տեխնիկական հարցերով զրուցիր @HaykTarkhanyan հետ։

http://qarakusi.am/problem/12189/solution

**Comment by a-arakelian** [comment]
Բարև @hakob17  սա - @ srohund իմ տելեգրամն ա, կարաս ստեղ գրել, կամ էլ ֆեյսբուքով - m.me/mahamorm

**Comment by HaykTarkhanyan** [comment]
Ողջույն @hakob17, ինչպեսա՞ պրոգրեսը, ինչո՞վ կարանք օգնենք

**Comment by gogyan** [comment]
@narek-mkrtumyan  սա մոնտաժած կա՞

**Comment by narek-mkrtumyan** [comment]
@gogyan հա, նույնիսկ փաբիլք ա

https://www.youtube.com/watch?v=pxvih4J1z6I
