### ISSUE TITLE
Հ7, վիճակագրություն - դաս 2։ Դասի հասնելու ժամանակը

### ISSUE THREAD

**Issue by gogyan** [qarakusi-am/qarakusi.am#140]
1. Էկրանի աջ մասում նկարել դպրոց, հետո մեջտեղի մասերում դպրոցական պայուսակով աշակերտ։
2. Աշակերտի վերևը գրել "Հունվարի 30 –> 15 րոպե" ու այդ ընթացքում աշակերտից դեպի դպրոց երկար սլաք նկարել։
3. Աշակերտի վերևը, արդեն գրված տեքստի տակ գրել "Հունվարի 31 –> 10 րոպե"
4. Դպրոցը, աշակերտին ու երկար սլաքը ջնջել, որ մնան միայն գրված երկու տողերը։
5. Եղած տեքստի տակը գրել (8 տող) Փետրվարի 1   –> 15 րոպե, Փետրվարի 2   –> 14 րոպե, Փետրվարի 3–> 17 րոպե, Փետրվարի 6–>14 րոպե, Փետրվարի 7 –> 11 րոպե, Փետրվարի 8 –> 15 րոպե, Փետրվարի 9–>14 րոպե, Փետրվարի 10–>15 րոպե:
6. Սլաքները ջնջել ու ամբողջը սարքել 11 տողանի աղյուսակ, որի առաջին տողի առային վանդակում գրել "Օր", իսկ երկրորդում՝ "Ժամանակ"։
7.  Բոլոր տվյալների opacity–ն փոքրացնել, բացառությամբ աղյուսակի երկրորդ տողի։
8. Երկրորդ տողի opacity–ն փոքրացնել ու զուգահեռ երրորդ տողի opacity–ն մեծացնել։
9. Բոլորի opacity–ները վերականգնել նորմալ վիճակի։
10. Աղյուսակի կոնտուրները ջնջել, առաջին սյունակը ջնջել, թողնել միայն երկրորդ սյունակի թվերը՝ րոպե բառերը նույնպես ջնջել։
11. Ստացված սյունակով գրված թվերը վերադասավորել մի տողով, որ դասավորված լինեն աճման կարգով, իրարից բաժանված ստորակետով։ Այնպես անել, որ էկրանի երկարության 80%–ով գրված լինեն ու լինեն էկրանի մեջտեղից թեթևակի ներքև։
12. Թվերից ամենափոքրը՝ 10-ը և ամենամեծը՝ 17-ը, մեծացնել, տատանել ու էլի փոքրացնել։
13. Էկրանի վերևում գրել  17 - 10 = 7, այնուհետև նկարել հորիզոնական սլաք ու սլաքի ծայրում գրել "Լայնք"
14. Բոլոր թվերի կոպիան սարքել, բարձրացնել վերև ու բոլոր ստորակետերը սարքել +։
15. Ստացված արտահայտության տակը դնել երկար կոտորակի գիծ ու հայտարարում գրել 10։
16. Ստացված կոտորակը գրել = 140/10 = 14:
17. Կոտորակը ջնջել, 14 թիվը տանել ձախ՝ 17-10-ի տակն ու կողքից ավելացնել " րոպե –> միջին ժամանակը (միջին թվաբանականը)"
18. Տվյալներից 15 թվերը սարքել կարմիր, մեծացնել, տատանել ու էլի փոքրացնել, բերել սովորական տեսքի, բայց թողնել կարմիր։
19. 15 թվերի վերևը գրել "Մոդ" բառը։
20. 15 և մոդ բառերը տանել վերև, որ վերևի երկու տողերի տակը հայտնվեն ու դառնա "15 րոպե -> մոդ"
21. Թվերը վերադասավորել, որ ամեն տողում լինեն իրար հավասար թվերը, ընդ որում վերևից ներքև լինեն դասավորված աճման կարգով․ 
  10
  11
  14,14,14
  15,15,15,15
  17
22. Սարքել երկու սյունականոց և 6 տողանոց աղյուսակ, որ երկրորդ սյունակում լինեն վերևի թվերը, բայց առաջին տողը լինի դատարկ։
23. Ամեն տողի առաջին տվյալի քոփին անել ու բերել առաջին սյունակ։
24. Երկրորդ սյունակից ամեն վանդակում եղած տվյալը տրանսֆորմ անել իրենց քանակը նկարագրող թվի։
25. Աղյուսակի առաջին տողում գրել "Տվյալ" և "Քանակ" բառերը։
26. Աղյուսակից աջ գրել "հաճախականային աղյուսակ"։

**Comment by lilithm98** [comment]
knereq isk svg nery ashxatem gunavor ogtagorcel te sev u spitak?

**Comment by gogyan** [comment]
Գունավոր ենք օգտագործում։

**Comment by lilithm98** [comment]
exav shnorhakalutyun
