### ISSUE TITLE
Հ7, վիճակագրություն - դաս 3։ հաճախելիություն ըստ շաբաթվա օրերի 

### ISSUE THREAD

**Issue by gogyan** [qarakusi-am/qarakusi.am#149]
1. Նախորդ վիդեոյի 10 տվյալները կրկին գրել էկրանին, կենտրոնից թեթևակի ձախ ( հունվարի 30 -» 15 րոպե,....)
2. Առաջին 5 օրերի կողքը, աջից ձևավոր փակագիծ նկարել ու կողքը գրել "5 հաջորդական օրեր"
3. "հունվարի 30" տեքստը փոխել ու սարքել երկուշաբթի, հետո թեթևակի մեծացնել ու նորից փոքրացնել։
4. Աջ մասում գրված ձևավոր փակագիծն ու "5 հաջորդական օրեր" ջնջել։
5. Տակի ամսաթվերը սարքել շաբաթվա օրեր (շաբաթվա ամեն օրից 2 հատ կլինի): Սա պետք է բոլորը միաժամանակ անել։
6. 6-10 տողի տվյալները "14րոպե,․․․" բոլորը տանել վերև, համապատասխան շաբաթվա օրվա տվյալի կողքը։ Կստացվի այսպես․ "Երկուշաբթի –» 15 րոպե, 14 րոպե" ընդամենը 5 տող։ Սա անելիս միաժամանակ 6-10 տողերի երկուշաբթի, երեքշաբթի,․․․ բառերը ջնջի։
7. Սլաքները ջնջի ու ամբողջը տեղավորի 2 սյունականոց աղյուսակի մեջ։
8. Երեքշաբթի օրվա տողը մատնանշի, մնացածի opacity–ն փոքրացրու։
9. Opacity—ները դզի, թող գա հին տեսքի։

**Comment by lilithm98** [comment]
knereq isk 6 rd ketum miajamanak bardzracnem ropenery? te bardzracnem n erord toxiny u ira shabatva ory jnjem, heto hajordy?

**Comment by gogyan** [comment]
6-րդ տողը արա, հետո 7-10 միասին արա
