### ISSUE TITLE
P11334 - Ստեփանյանների 5 աղջիկները

### ISSUE THREAD

**Issue by gogyan** [qarakusi-am/qarakusi.am#15]
http://qarakusi.am/problem/11334/solution

@HaykTarkhanyan  սարքելուց առաջ զրուցիր իմ կամ @a-arakelian  հետ։

**Comment by narek-mkrtumyan** [comment]
ձայնագրությունը
https://youtu.be/wm5PaTJAHlE

**Comment by narek-mkrtumyan** [comment]
https://youtu.be/xgy37_2-XM8
