### ISSUE TITLE
P11159 - the geese and ducks

### ISSUE THREAD

**Issue by gogyan** [qarakusi-am/qarakusi.am#16]
http://qarakusi.am/problem/11159/solution

Անելուց զրուցել @gogyan  կամ @narek-mkrtumyan  հետ։

**Comment by narek-mkrtumyan** [comment]
https://www.youtube.com/watch?v=lNp0bo1Sgj4

**Comment by gogyan** [comment]
@Vachagan11  սրա վերջնական տարբերակը կա՞, թե երկու հատ վիդեո է ամենքը մի լուծման մասին

**Comment by gogyan** [comment]
Դե վերջնական վիդեոյի հղումը դիր,  կոդերը ուղարկի ստեղ ու ուղարկի ռեվյուի։

**Comment by Vachagan11** [comment]
Եթե դեմ չեք, շաբաթ օրը անեմ, որտև կոմպս տանն է

**Comment by Vachagan11** [comment]
https://www.youtube.com/watch?v=L4R52TwG7Xw

վերջնական վիդեոյի հղումը
