### ISSUE TITLE
library for mixtures

### ISSUE THREAD

**Issue by gogyan** [qarakusi-am/qarakusi.am#2]
Create a functionality to solve problems on solutions/mixtures/compositions of materials.
The unit of the animation is a rectangle box with open upside that contains some amount of "liquid".
In the bottom of the box it shows the amount in grams/kg/l etc, in the center of the box it shows some percentage, bottom left side shows some amount (usually the amount of salt/sugar etc... in the mixture). 

In the final animation we have BOX1 + BOX2 = BOX 3 (the number of boxes might change).
For example "how much water must be added to the 300g of mixture (20% is salt) to get 12% of salt mixture.

| -----------|~~~~~ |-------------|~~~~ |-----------|
| -----------|~~~~~ |-------------|~~~~ |-----------|
| ----20%--|~~~+~ |-----0%-----|~~=~~|~~12%~|
| -----------|~~~~~ |-------------|~~~~ |-----------|
|!!!!!!!!!!!!!!!!|~~~~~ |!!!!!!!!!!!!!!!!!!!|~~~~ |!!!!!!!!!!!!!!!|
~~300g                      

Above is the visualization of the problem. When solving the following views we will have.
STEP1. First box contains 60g of salt, the second box contains 0g of salt (first we show 60 then 0).
| -----------|~~~~~ |-------------|~~~~ |-----------|
| -----------|~~~~~ |-------------|~~~~ |-----------|
| ----20%--|~~~+~ |-----0%-----|~~=~|~~12%~~|
| -----------|~~~~~ |-------------|~~~~ |-----------|
|!60g!!!!!!!!!|~~~~~ |!!!0g!!!!!!!!!!!!|~~~~ |!!!!!!!!!!!!!!!|
~~~300g                      

STEP2. The 3rd box contains 60+0=60g of salt (these 3 parameters 60,0,60 must have the same color and connected to be able blink all of them together, or change the font size together).
| -----------|~~~~~ |-------------|~~~~ |-----------|
| -----------|~~~~~ |-------------|~~~~ |-----------|
| ----20%--|~~~+~ |-----0%-----|~~=~|~~12%~~|
| -----------|~~~~~ |-------------|~~~~ |-----------|
|!60g!!!!!!!!!|~~~~~ |!!!0g!!!!!!!!!!!!|~~~~ |!!60g!!!!!!!!!!|
~~~300g                      

STEP3. Since in the 3rd box 60g is the 12% of the total weight, then the total weight is 100*60/12=500g
| -----------|~~~~~ |-------------|~~~~ |-----------|
| -----------|~~~~~ |-------------|~~~~ |-----------|
| ----20%--|~~~+~ |-----0%-----|~~=~|~~12%~~|
| -----------|~~~~~ |-------------|~~~~ |-----------|
|!60g!!!!!!!!!|~~~~~ |!!!0g!!!!!!!!!!!!|~~~~ |!!60g!!!!!!!!!!|
~~~300g~~~~~~~~~~?~~~~~~~~~~~500g                      

STEP4.  ? = 500-300=200g. All parameters 300,? and 500 must be connected to be able blink all of them together, change font size, change color etc.
| -----------|~~~~~ |-------------|~~~~ |-----------|
| -----------|~~~~~ |-------------|~~~~ |-----------|
| ----20%--|~~~+~ |-----0%-----|~~=~|~~12%~~|
| -----------|~~~~~ |-------------|~~~~ |-----------|
|!60g!!!!!!!!!|~~~~~ |!!!0g!!!!!!!!!!!!|~~~~ |!!60g!!!!!!!!!!|
~~~300g~~~~~~~~~~200g~~~~~~~~500g

**Comment by a-arakelian** [comment]
Out of date
