### ISSUE TITLE
մտավախություն ունեմ որ խնդիր ունենք `maserovkhndirner.py`-ի հետ, objects-ում SVG_files դիրեկտորիա կա, որի մեջ որ scissors-նա իսկ մենք ուղիղ ենք իմպոռտ անում

### ISSUE THREAD

**Issue by HaykTarkhanyan** [qarakusi-am/qarakusi.am#20]
```  File "C:\Users\User\Desktop\qarakusi.am\lib\maserovkhndirner.py", line 19, in <module>
    from objects import Scissors
ModuleNotFoundError: No module named 'objects'
```

Հ․ Գ․ չեմ փոխում իմպոռտը որ համոզվենք իսկականից խնդիրը կա նոր push անեմ

**Comment by zidder** [comment]
Մտավախություն ունեմ, որ README-ն չես կարդացել ։(

**Comment by zidder** [comment]
Եթե windows է` Վաչագանը README-ն կթարմացնե, կդզվի

**Comment by HaykTarkhanyan** [comment]
վինդովսով եմ, իմ setup-ով էի վազացնում, makefile-ը կարդալուց չէի հասկացել որ դիրեկտորիաների խնդիրը լուծումա։

Փակում եմ issue-ն որովհետև իմ սխալից էր փաստորեն, մերսի։

**Comment by zidder** [comment]
@Vachagan11 կռնաս windows֊ի մասին PR էնելուց հետո փակես issue֊ն :)
