### ISSUE TITLE
(a^m)^n = a^mn վիզուալ ապացուցում

### ISSUE THREAD

**Issue by gogyan** [qarakusi-am/qarakusi.am#29]
(а^m)^n = a^m *
                   a^m * 
                   ..........
                   a^m *
                
Ամեն տողը սարքել a * a * ... * a ու բոլոր a–երը վերցնել մեծ ուղաղնկյան մեջ ու կողմերի վրա նշել m և n թվերը։

**Comment by a-arakelian** [comment]
Done
