### ISSUE TITLE
Հ5-1 թվային առանցքի վրա գումարում և հանում  

### ISSUE THREAD

**Issue by gogyan** [qarakusi-am/qarakusi.am#37]
1․ Նկարել 7 հատ խնձոր։ Հետո կողքից ավելացնել ևս երկու խնձոր ու գրել 7+2=9:
2. Արդեն նկարածը տանել վերև (կամ էլ հենց սկզբից նկարել վերևում), մեջտեղում նկարել թվային առանցքը 0-ից մինչև 11 (կարելի է քանոնի տեսքով)։ 7-ի վրա նկարել ինչ որ կենդանի, ասենք թե մորեխ։ Մորեխը երկու անգամ թռնում է աջ ու հայտնվում 9 կոորդինատով կետում։ Կրկին գրել 7+2=9 (կամ էլ արդեն եղածը մեծացնել–փոքրացնել):
3․ Էկրանի ներքևի մասում գրել 9-4 = ?
4. Խնձորներից չորս հատը տանել էկրանից դուրս ու մորեխին չորսը քայլով տեղափոխել ձախ։
5. ?–ը փոխարինել 5-ով։

**Comment by narek-mkrtumyan** [comment]
@a-arakelian էս էլ ձայնագրությունը

https://youtu.be/zl3xXM5PaS0

**Comment by a-arakelian** [comment]
Անիամացիան սարքել եմ, սլեքում ա
@narek-mkrtumyan  ձայնագրությունը կողարկես, որ մոնտաժեմ

**Comment by a-arakelian** [comment]
Done
