### ISSUE TITLE
Վարժություններ միանդամի կատարյալ տեսքի մասին

### ISSUE THREAD

**Issue by narek-mkrtumyan** [qarakusi-am/qarakusi.am#52]
https://www.youtube.com/watch?v=-C_pMKwxeG4

Երևի արժի նախօրոք մի հատ ֆունկցիա գրել, որը միանդամի մեջի տառեր թվերը վերադասավորում ա

![IMAGE 2022-09-17 23:33:27](https://user-images.githubusercontent.com/81069641/190873639-151d3e77-331f-40bb-b7d9-d609da580784.jpg)

**Comment by gogyan** [comment]
#28֊ն է, Գոռինն է։ Թե արդեն պետք է արագացնենք։

**Comment by narek-mkrtumyan** [comment]
ֆունկցիաները գրել եմ, հեսա PR-ս հաստատվի, դրանցողվ արագ-արագ գրվող բան ա
