### ISSUE TITLE
Run simple problem on Windows 

### ISSUE THREAD

**Issue by gogyan** [qarakusi-am/qarakusi.am#8]
Run a simple problem (for example 22 runners problem) on Windows using utilities Areg created.
Maybe need to talk with Areg.

**Comment by sssilver** [comment]
I think a good strategy would be to simply create the entire code in a `run()` function in a new problem script under `problems/`, just to get it to run.

From there we can distill the problem-agnostic/boilerplate code, and decide where we wanna move it and what we want it to look like.

**Comment by a-arakelian** [comment]
To be honest, I'm not getting into what I need to do. There are a lot of things in the README file that I don't understand, and I don't understand what our goal is. I would be very grateful if someone would explain in a simple (extended) form exactly what I need to do (check).

**Comment by gogyan** [comment]
put your running code in github, assign the task to @sssilver , he will made appropriate changes and will assign you back.

**Comment by a-arakelian** [comment]
![Untitlsed](https://user-images.githubusercontent.com/99004923/170234316-815929a0-9900-4f93-add8-c8f64e237447.png)
There some problems with pushing new branch to github

**Comment by sssilver** [comment]
@a-arakelian looks like you haven't added your public SSH key to your Github account, hence the issue.

Follow directions [here](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/checking-for-existing-ssh-keys), and then re-try cloning once you're done setting it up.
