### ISSUE TITLE
11375 գնացքն անցնում է ուղևորի կողքով

### ISSUE THREAD

**Issue by gogyan** [qarakusi-am/qarakusi.am#83]
http://qarakusi.am/problem/11375/solution

@a-arakelian  դու այսպիսի բան սարքելու մեծ փորձ ունես։ Հովհաննեսի հետ անընդհատ կապի մեջ եղիր, որ արագ ու ճիշտ ստացվի մոտը։

1.  Պատկերել քաղաքի ֆոն խոշոր պլանով, այնուհետև գնացք, որը շարժվում է (երկու օբյեկտների svg ֆայլերը պահոցում կան)։
2․ Պլանը փոքրացնել, որ գնացքն ավելի փոքր լինի: Գնացքի շարժվելը կանգնեցնել, տակը ձևավոր փակագիծ դնել ու գրել 280 մ, գնացքի վրա գրել 72 կմ/ժ։  
3. Ճանապարհին, գնացքից առաջ պատկերել մարդու (svg ունենք):
4. Գնացքը շարժվելով անցնում է մարդու կողքով ու առաջ գնում, էկրանից դուրս գալիս։
5. Գնացքը հետ շարժել, մինչև առաջնամասը լինի մարդու մոտ։ 
6. Սարքել գնացքի կլոնը, օփասիթին փոքրացնել ու իջեցնել ներքև։
7. Գծել վայրկյանաչափ, գնացքի շարժվելու ընթացքում սլաքը պտտել։
8. Գնացքը շարժել, մինչև գնացքի հետևի մասը հասնի մարդուն։
9. Մարդուն ջնջել։
10. Երկու գնացքների առաջնամասերով ուղղաձիգ կետագծեր գծել։ 
12. Ստացված ուղղաձիգ գծերի արանքում գրել 280 մ։
(այնպես անել, որ եղած պատկերը լինի էկրանի մեջտեղում։
13. Ստացված պատկերը էկրանի 20% չափով վերև տանել։
14.  Գրել 1ժ –> 72 կմ
15. Տակը գրել 1ժ = 60 ր = 60 * 60 վ =3600 վ։
16. Ստացված "3600 վ" տեղափոխել ու գրել 14-րդ կետի 1ժ փոխարեն ու այդ ընթացքում 15 կետում գրված տեքստը ջնջել։
17. 14-րդ կետի 72 կմ տրանսֆորմ անել 72000 մ։
18. ստացված 3600 վ –> 72000 մ արտահայտության տակ գրել 1 վ -» ?
19. 14 և 18 կետերի ստացված համեմատականությունը վերցնել դեղին ուղղանկյան մեջ ու աջից գրել ? = 1 * 72000 / 3600 = 20 մ։ 
20. 280 մ տեքստի վերևում գրել գնացքը շարժվում է 20 մ/վ արագությամբ։
21. 19-րդ կետի տեքստ տակ գրել 280 : 20 = 14 վ։

**Comment by AlternativeFuture** [comment]
2․ Պլանը փոքրացնել, որ գնացքն ավելի փոքր լինի
Նկատի ունեք գնացքը ընթացքի ժամանակ փոքրանա համ էլ քաղաքը զուգահեր գնացքին փոքրանա՞
