### ISSUE TITLE
(a+b)(c+d) և a(b+c+d)

### ISSUE THREAD

**Issue by gogyan** [qarakusi-am/qarakusi.am#94]
տեքստը @Vachagan11 –ից,
անիմացիան @a-arakelian  ու @tmargary

**Comment by Vachagan11** [comment]
https://www.dropbox.com/scl/fi/c3fv9bh24asr9mpw3al28/13-a-b-c-d.gdoc?dl=0&rlkey=a6uk9znw0b5vzyugo4drtqeka

**Comment by Vachagan11** [comment]
https://www.dropbox.com/scl/fi/hukgd88a9abw041dmn4rm/12-a-b-c-d.gdoc?dl=0&rlkey=hqhiqjklprdt05riagnowa4kc
